GAI
karasevNew/miit pull request #1
Opened 2023-02-25 09:51 UTC by karasevNew

2023-03-30 13:23 UTC, MarinaPaley requested changes
Почему у Вас нет файла .gitignore?
Без сдачи экзамена за 1 семестр 4 курса я ничего проверять не буду.

2023-03-30 13:26 UTC, karasevNew commented
@MarinaPaley Экзамен я Вам сдал вместе с Ивановым. У меня были проблемы с диаграммой долгое время, но в самом конце я ее правильно построил и Вы работу приняли

2023-03-30 13:28 UTC, karasevNew commented
@MarinaPaley Также мы сдали все лабораторные, только другого варианта. Того, который был нужен, мы не смогли найти, так как из группы мы были удалены.

2023-03-30 13:34 UTC, MarinaPaley commented
@karasevNew 1 семестр (СУБД)

2023-03-30 13:37 UTC, karasevNew commented
@MarinaPaley Ах, там у меня ДЛС тема была, я только нулевое задание не сделал. Если оно необходимо, то я им займусь сейчас

2023-03-30 13:43 UTC, karasevNew commented
@MarinaPaley 
![изображение](https://user-images.githubusercontent.com/126322804/228855570-2af56989-d4b7-4335-9a7c-e5bbf432d083.png)
Марина Алексеевна, это ведь надо сделать?

2023-03-30 13:49 UTC, karasevNew commented
@MarinaPaley Если Вы не против, я сделаю какой-нибудь любой вариант? Я просто не помню, какой я тогда был по списку

2023-03-30 14:00 UTC, MarinaPaley commented
@karasevNew делайте любой, по ДЛС что-то было не до конца сделано.

2023-03-30 14:02 UTC, karasevNew commented
@MarinaPaley про Длс Вы вроде как приняли, там были только незначительные моменты. А нулевое да, задолжал, так что сделаю, как обещал)

2023-03-30 17:13 UTC, MarinaPaley commented
@karasevNew Покажите `approve` по `LDS`
да, СУБД - С++

2023-03-30 21:32 UTC, karasevNew commented
@MarinaPaley Вы вроде в гите не апрувнули, но на переэкзаменовке работу приняли). Там по мелочи оставалось: дописать gitignore и добавить в некоторых местах count. Позвольте, пожалуйста, сначала сделать нулевую работу и досдать материал за этот семестр. Боюсь, что если я сейчас сяду вспоминать ту старую работу, то ничего не успею

2023-03-31 07:36 UTC, MarinaPaley commented
@karasevNew на какой переэкзаменовке? нет `approve` - нет экзамена

2023-03-31 08:43 UTC, karasevNew commented
@MarinaPaley Хорошо, я добавлю где нужно const и gitignore, и, надеюсь, что с той работой будет закончено

2023-03-31 10:27 UTC, MarinaPaley commented
@karasevNew не факт, там были тесты? Про все остальное я не помню.

2023-03-31 10:33 UTC, karasevNew commented
@MarinaPaley Да, все было, работу показывал. Я исправлю то, что Вы указали

2023-03-31 10:36 UTC, karasevNew commented
@MarinaPaley Я ведь тогда не совсем прям с пустыми руками приходил)

2023-03-31 11:12 UTC, karasevNew commented
@MarinaPaley 

![4](https://user-images.githubusercontent.com/126322804/229105175-c297a6bb-9193-42b5-bef8-028ac7ccb9a4.jpg)
![3](https://user-images.githubusercontent.com/126322804/229105177-a5126d61-af22-408c-a4ca-6a93abf22c4e.jpg)
![2](https://user-images.githubusercontent.com/126322804/229105178-850fa11f-19da-454d-98f4-95dfdd5df1e5.jpg)
![1](https://user-images.githubusercontent.com/126322804/229105180-2a4f4ee7-4929-417c-9353-1dee3122b673.jpg)
![5](https://user-images.githubusercontent.com/126322804/229105184-80d47039-acc2-4368-9469-0de690382544.jpg)
Тут список того, что Вы сказали мне поправить. Тесты есть, остальное Вы приняли

2023-04-02 18:46 UTC, karasevNew commented
@MarinaPaley Доброго времени суток, Марина Алексеевна. Загрузил нулевую работу.

2023-04-04 14:42 UTC, karasevNew commented
@MarinaPaley Добрый вечер, Марина Алексеевна. Мой PR дошел до Вас?

2023-04-11 10:05 UTC, closed without merging