0 and DLS
karasevNew/miit pull request #3
Opened 2023-04-02 19:44 UTC by karasevNew

2023-04-05 10:18 UTC, MarinaPaley requested changes
1. Отсутствует файл .gitignore. Я НЕ должна проверять 88 файлов. А клонировать Ваш репозиторий в таком виде не хочу, так как он загрузить мне ненужные файлы.
2. Отделяйте в тестах каждый пункт `Arrange`, `Act`, `Assert`. Проверяйте только одну функциональность.
3. Каждый тест отделяйте пустой строкой друг от друга

2023-04-05 10:18 UTC, MarinaPaley commented on DLS/DLS/DLS.h
> +	* \param value целое число
Что такое `pos`?

2023-04-05 10:18 UTC, MarinaPaley commented on DLS/DLS/DLS.h
> +	* \param pos целое число
Как используется это "целое число", что оно целое видно из типа. Что это?

2023-04-05 10:18 UTC, MarinaPaley commented on DLS/DLS/DLS.h
> +	* \param pos целое число > 0
Также

2023-04-05 10:18 UTC, MarinaPaley commented on DLS/DLS/DLS.h
> +		~DLSElement();
зачем Вам деструктор? Класс захватывает ресурсы?

2023-04-05 10:18 UTC, MarinaPaley commented on DLS/DLS/DLS.h
> +	DLS operator= (const DLS& rhs) = delete;
Почему?
Почему только этот оператор?

2023-04-05 10:18 UTC, MarinaPaley commented on DLS/DLS/DLS.h
> +
Остальная документация где?

2023-04-05 10:18 UTC, MarinaPaley commented on DLS/DLSTests/DLSTests.cpp
> +			Assert::IsTrue(!result.IsEmpty() && expected == result.GetSize() && result.ToString() == "1, 2, 3, 4, 5");
Тест должен проверять одну функциональность

2023-04-05 10:18 UTC, MarinaPaley commented on DLS/DLSTests/DLSTests.cpp
> +		TEST_METHOD(TestDLSCreation)
[Naming](https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices#naming-your-tests)

2023-04-05 21:06 UTC, karasevNew commented
@MarinaPaley Вы правы, Марина Алексеевна. Я тогда перезалью в четверг работу исправленную уже с гит игнором

2023-04-06 17:24 UTC, karasevNew commented
@MarinaPaley Марина Алексеевна, сделал всё по-людски. Перезалил с гитигнором и ГАИ, и ДЛС с 0 работой

2023-04-07 11:46 UTC, karasevNew commented
Марина Алексеевна, доброго времени суток! Посмотрите, пожалуйста, по возможности,  два моих новый PR. Я все исправил и сделал.

2023-04-10 13:40 UTC, karasevNew commented
@MarinaPaley Добрый день, Марина Алексеевна. Посмотрите, пожалуйста, мои работы

2023-04-11 08:18 UTC, MarinaPaley requested changes
90 файлов на ревью, Вы серьезно?

2023-04-11 11:54 UTC, closed without merging